//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1061109_FirstNetMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComSupplier
    {
        public string SuppID { get; set; }
        public string SuppName { get; set; }
        public string SuppNameS { get; set; }
        public string SuppClassID { get; set; }
        public string Trade { get; set; }
        public string InvoName { get; set; }
        public string RegionID { get; set; }
        public string ZipCode { get; set; }
        public string Address { get; set; }
        public string ZipCode1 { get; set; }
        public string Address1 { get; set; }
        public string ZipCode2 { get; set; }
        public string Address2 { get; set; }
        public string ZipCode3 { get; set; }
        public string Address3 { get; set; }
        public string TaxNo { get; set; }
        public string ChiefName { get; set; }
        public Nullable<decimal> CapTAL { get; set; }
        public string LinkMan { get; set; }
        public string LinkTitle { get; set; }
        public string FaxNo { get; set; }
        public string TelNo { get; set; }
        public string TelNo1 { get; set; }
        public string TelNo2 { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string EmplID { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public string CreateDate { get; set; }
        public string StopDate { get; set; }
        public string DeliID { get; set; }
        public Nullable<short> InvoMode { get; set; }
        public string SuppID_I { get; set; }
        public Nullable<short> TaxWay { get; set; }
        public Nullable<short> InvoType { get; set; }
        public string CurrencyID { get; set; }
        public Nullable<bool> IsTax { get; set; }
        public string ActNo { get; set; }
        public string BankID { get; set; }
        public string PurDate { get; set; }
        public string PurRDate { get; set; }
        public string Sub_AP { get; set; }
        public string Sub_NP { get; set; }
        public string Sub_ADVSupp { get; set; }
        public string SuppID_R { get; set; }
        public string CustID_R { get; set; }
        public Nullable<short> APMode { get; set; }
        public Nullable<short> APDay { get; set; }
        public Nullable<short> NPMode { get; set; }
        public Nullable<short> NPDay { get; set; }
        public Nullable<decimal> APLimit { get; set; }
        public Nullable<decimal> CheckLimit { get; set; }
        public Nullable<decimal> NotCashCheck { get; set; }
        public Nullable<decimal> CreditSum { get; set; }
        public Nullable<decimal> BeginAP { get; set; }
        public Nullable<decimal> BeginADV { get; set; }
        public Nullable<decimal> APSum { get; set; }
        public Nullable<decimal> AdvSum { get; set; }
        public Nullable<decimal> UnChkAP { get; set; }
        public Nullable<decimal> UnChkADV { get; set; }
        public string SuppNameEn { get; set; }
        public string SuppNameSEn { get; set; }
        public string Conditions { get; set; }
        public string LinkManEn { get; set; }
        public string LinkTitalEn { get; set; }
        public string Payment { get; set; }
        public string DeliWay { get; set; }
        public string Sub_CommiR { get; set; }
        public string Sub_Commi { get; set; }
        public string MarkID { get; set; }
        public string SuppGrade { get; set; }
        public string Explain { get; set; }
        public string Memo { get; set; }
        public string UdefT1 { get; set; }
        public string UdefT2 { get; set; }
        public string UdefT3 { get; set; }
        public string UdefD1 { get; set; }
        public string UdefD2 { get; set; }
        public Nullable<decimal> UdefN1 { get; set; }
        public Nullable<decimal> UdefN2 { get; set; }
        public Nullable<short> RecDay { get; set; }
        public string Pointude { get; set; }
        public string Pointude1 { get; set; }
        public string Pointude2 { get; set; }
        public string Pointude3 { get; set; }
        public string AppxPath { get; set; }
    }
}
